- README.md
- src/input.rs
- src/nodes/player.rs
This is my proposal for improved default key bindings for both player 1 and player 0.
related: #72
> improve default key bindings

- Cargo.lock
- Cargo.toml
- README.md
- src/gui.rs
- src/gui/main_menu.rs
- src/input.rs
- src/main.rs
- src/nodes/local_network.rs
- src/nodes/network.rs
Made a simple "lobby" UI to choose input device for each of the fish on the game start
https://user-images.githubusercontent.com/910977/132953528-0ef09afa-3df7-4983-ba09-38e3c1808377.mp4
> Gamepad support

- src/gui/main_menu.rs
While on the "Network Game" menu, FishFight crashes if "Relay Server" is selected and "Connect" is pressed when the opponent address is not a valid `u64`. This PR adds a return value (`bool`) to the `connect` function and checks this value upon connection attempts for preventing the function from panicking thus keeps the GUI running on such trivial errors.
> prevent crash on invalid opponent address for relay connection

- src/items.rs
- src/items/shoes.rs
- src/nodes/player.rs
In compare to old shoes implementation i added `PhysicsBody` and `ThrowableItem` to it, and made that shoes drops from the killed fish.
Closes https://github.com/fishfight/FishFight/issues/108
> Shoes reimplementation

- src/items/shoes.rs
Two days i tried to figure out what's wrong 😄
> Fix shoes drawing rotation

- src/gui/background.rs
- src/gui/create_map.rs
- src/gui/main_menu.rs
- src/gui/mod.rs
- src/main.rs
> main menu background

- .github/workflows/release.yml
This PR includes the changes for making the release workflow run smoothly as possible. A few notable points are:
- Switch to [svenstaro/upload-release-action](https://github.com/svenstaro/upload-release-action)
- Workflow is now triggered via `push` event so it will eliminate the cases where it is triggered by creating a branch.
- Line endings changed to `LF` for consistency with other workflows.
#236
> Update the release workflow

- src/editor/actions.rs
- src/editor/gui/editor_menu.rs
- src/editor/gui/mod.rs
- src/editor/gui/windows/create_layer.rs
- src/editor/gui/windows/load_map.rs
- src/editor/gui/windows/mod.rs
- src/editor/gui/windows/save_map_as.rs
- src/editor/history.rs
- src/editor/mod.rs
- src/game/scene.rs
- src/gui/create_map.rs
- src/gui/game_menu.rs
- src/gui/main_menu.rs
- src/gui/menu.rs
- src/gui/style.rs
- src/json/map/mod.rs
- src/json/map/tiled.rs
- src/map.rs
- src/resources.rs
This enables saving and loading of maps in the editor
> Editor io actions

- src/player/events.rs
- src/player/mod.rs
Player collision event now works as it should
> Collision player event

- assets/player_characters.json
- assets/player_characters.schema.json
- src/components/animation_player.rs
- src/components/sprite.rs
- src/game/scene.rs
- src/gui/background.rs
- src/gui/create_map.rs
- src/gui/main_menu.rs
- src/gui/menu.rs
- src/gui/mod.rs
- src/gui/panel.rs
- src/gui/select_character.rs
- src/gui/style.rs
- src/json/render.rs
- src/main.rs
- src/player/character/animations.rs
- src/player/character/mod.rs
- src/player/mod.rs
- src/resources.rs
- src/text.rs
This adds customizable player characters, defined in `assets/player_characters.json`, and a character selection window when creating a local game.
It is possible to customize metadata, like name and description, cosmetics, such as texture, scale and animations, as well as gameplay-related parameters, such as movement speed and jump force.
This should allow more freedom when designing characters and open up for some interesting possibilities when mod loading is implemented in the near future.
> Player character definition and selection

- Cargo.lock
- Cargo.toml
- src/data.rs
- src/error.rs
This PR makes the following changes in `Cargo.toml`:
- `license` and `description` sections are added.
- `authors` section is updated to something more general since we have `CREDITS.md` now.
- Unused dependencies are removed.
- Formatting: reordered the dependencies/sections & removed newlines.
> Update Cargo.toml & remove unused dependencies

- PACKAGING.md
This PR adds `PACKAGING.md` file to the repository which goes through the steps of building and packaging Fish Fight.
> Add PACKAGING.md

- src/effects/active/mod.rs
This makes debug shapes for active effect colliders entities, in stead of storing them in static containers.
It also changes TTL of these shapes to be based on timers in stead of frame counts
> Use ECS for effect debug shapes in stead of static containers

- src/drawables/mod.rs
- src/effects/active/triggered.rs
- src/items.rs
- src/map/sproinger.rs
- src/player/animation.rs
- src/player/inventory.rs
This adds getters to `Drawable`
> Add getters to Drawable

- assets/items/cannon.json
- assets/particle_effects.json
- assets/particle_effects/cannon_cannonball_smoke.json
- src/effects/active/triggered.rs
- src/physics.rs
This PR is part of https://github.com/fishfight/FishFight/issues/120
> Cannon juicing

- src/editor/mod.rs
- src/editor/tools/mod.rs
- src/editor/tools/placement.rs
This adds an update method to the `EditorTool` trait
> Add update method to tool trait

- PACKAGING.md
This PR updates packaging docs about the available environment variables.
> Update PACKAGING.md about environment variables

- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR is doing what title suggests.
> Add libudev to CI/CD dependencies

- LICENSE
- licenses/LICENSE-APACHE
- licenses/LICENSE-MIT
Yes, it is hard to believe but it is 2022 now. 🥥
> Update license copyright years

- src/drawables/animated_sprite.rs
- src/effects/active/triggered.rs
- src/gui/select_character.rs
- src/items.rs
- src/map/decoration.rs
`impl From<AnimatedSpriteMetadata> for Animated Sprite` and clean
up some of the code that could benefit from it.
This is just some cleaning up I did while working on some effect stuff and I thought it'd be good to keep in a separate PR for ease of review.
> Make Eaiser to Create Animated Sprites From Meta

- PACKAGING.md
- contrib/jumpy.desktop
A very basic file to run from Jumpy from desktop launchers.
For now I omitted the `Icon` field, can be added if icons are made.
> Add desktop file

- assets/map/elements/decoration/anemones/anemones.element.yaml
- assets/map/elements/decoration/seaweed/seaweed.element.yaml
- src/assets.rs
- src/map/elements.rs
- src/map/elements/decoration.rs
- src/metadata/map.rs
> Re-implement Seaweed and Anemones Decorations

- src/ui/pause_menu.rs
> Add Level Name Heading to Pause Menu

- assets/map/elements/item/grenade/grenade.element.yaml
- src/map.rs
- src/ui/main_menu/map_select.rs
- src/ui/main_menu/player_select.rs
- src/ui/pause_menu.rs
- src/utils.rs
> In game map select

- Cargo.lock
- Cargo.toml
> Bump Jumpy Version in Cargo.toml

- crates/matchmaker/Cargo.toml
> Bump Jumpy Matchmaker Version

- src/map/elements/grenade.rs
- fire-action should light it, not throw it.
- throw with drop-button. Gets thrown further based on character momentum.
- possible to pick up grenade again after it’s been thrown (by whoever).
> Change Grenade Mechanics

- core/src/elements/sproinger.rs
> fix: remove grace period from sproinger.

- core/src/map.rs
- core/src/player.rs
- Also fix crash when spawning with an AI on a map without a sword.
> fix: fix pathfinding through empty collision tiles.

- src/ui/main_menu/map_select.rs
The player selection was not being honored when starting user maps.
Closes: #706
> fix: fix player selection when starting user maps.

- core/src/physics.rs
- core/src/physics/collisions.rs
> fix: fix incorrect ground state detection when intersecting jump-through tiles.

- assets/default.core.yaml
300 seems like a better option when moving faster
Fixes: #717
> fix: increased camera padding to 300px.

- core/src/player.rs
this replaces the old logic which had all AI chase player 1. It's a small improvement which means they'll attack each other sometimes, and player 1 doesn't always have to be running away
> feat: let the AI choose their enemies and chase them.

- core/src/elements/grenade.rs
- core/src/player.rs
> fix: don't drop killed items.

- core/src/elements/musket.rs
> fix: fix musket reloading when dying holding it.

- core/src/bullet.rs
> fix: make bullets not collide with fall-through blocks.

- src/networking/lan.rs
- src/ui/main_menu/network_game.rs
> fix: fix network menu not resetting after exiting a network game.

- .gitignore
- src/ui/main_menu/network_game.rs
Address a couple network crashes around UI functionality
> fix: network UI crashes.

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- Also updated jumpy core's version to match Jumpy's version for simplicity.
> chore(release): bump crate versions.

- Cargo.lock
- includes an update to Shiftnanigans to trim out some dependencies.
> build: update dependencies.

- src/main.rs
- src/networking.md
- src/networking.rs
- src/networking/certs.rs
- src/networking/lan.rs
- src/networking/online.md
- src/networking/online.rs
- src/ui/main_menu/network_game.rs
- src/utils.rs
- Also prunes some unused code and re-organizes a couple module exports.
> docs: update networking documentation.

- src/debug.rs
- src/input.rs
- src/loading.rs
- src/localization.rs
- src/platform.rs
- src/prelude.rs
- src/session.rs
- src/ui.rs
- src/utils.rs
This finishes adding basic docs to almost everything other than the `ui` module, which is probably not super important right now.
> docs: add more jumpy crate API docs.

- src/ui/main_menu/settings/controls.rs
> fix: fix control settings menu resize issue.

- Cargo.lock
- Cargo.toml
- src/console.rs
- src/logs.rs
- src/main.rs
- src/prelude.rs
Adds console using bevy_console crate, likely should implement our own console down the line. Can be open with grvave key: `
bevy_log::LogPlugin does not allow us to specify a tracing layer to write logs to console, so I duplicated this plugin and modified slightly. There are a number of feature flags for bevy_log that are commented our here - I do not believe these should impact us. We should switch back to bevy's plugin if this feature is added.
I tested on wasm, logging still works (in browser console), however console is disabled in wasm due to limitations of bevy_console. Long term implementing our own console is a good idea for wasm support, hopefully color support, and additional control.
We can register console commands as seen in bevy_console docs, may be useful for cheats, debug …
> feat: add in-game console displaying logs.

- src/ui/main_menu/map_select.rs
There's an unexpected `ConfirmSelection(true)` network message sent to player 2, along with a mis-placed assertion that assumed the message was a map selection message.
This fixes the assertion, but leaves the warning about the unexpected network message un-addressed, except for a TODO comment explaining what's happening.
Fixes: #834
> fix: fix crash when second player selects player in online match second.

- Cargo.lock
- assets/locales/en-US/settings.ftl
- src/fullscreen.rs
- src/main.rs
- src/settings.rs
- src/ui/main_menu/settings.rs
- src/ui/main_menu/settings/graphics.rs
You can also toggle fullscreen with the F11 key.
> feat: make game start in fullscreen and add fullscreen setting.

- .github/workflows/release.yml
We will be making nightly builds manually when something interesting happens.
> ci: remove scheduled nightly builds.

- Cargo.lock
Includes a fix for user inputs being dropped randomly.
Resolves: #882
> build(deps): update dependencies, including bones.

- assets/locales/en-US/player-select.ftl
- src/ui/main_menu/player_select.rs
Fix a bug preventing you from switching your fish without first selecting one and then pressing back.
> fix: fix player selection in online play.

- Cargo.lock
- Cargo.toml
> fix(web): fix crash on web build due to missing `web` feature for puffin.

- Cargo.lock
- src/debug.rs
companion PR for: https://github.com/fishfolk/bones/pull/346
frame time window re-added to bones, this enables viewing it.
> feat(frame-time-diag): Add bones frame time diagnostics window.

- Cargo.lock
- Cargo.toml
- packs/devpack/pack.yaml
Fixing a crash in release that was in 0.11.0
> chore(release): Bump version to 0.11.1

- Cargo.lock
- Cargo.toml
- src/core/physics/collisions.rs
Should switch off git revision ocne new rapier release is published.
> chore(deps): Switch back to upstream Rapier (bug fix merged upstream)

- Cargo.lock
Update bones for the following fixes:
https://github.com/fishfolk/bones/commit/6b8d743ae4cc2216a013f6bc39899a60ec9570b1 (fix: Fix race condition on if EguiCtx is initialized before bones game)
https://github.com/fishfolk/bones/commit/cbe537f8d0640b03bf10d9217591c06d0a47af0c (fix: Fix Zero'd DenseMoveDir not representing no input.)
> chore(deps): Update bones for: EguiCtx crash fix + network desync fix

- Cargo.lock
Update bones to get a fix for issue causing desync in 3+ player matches.
> chore(deps): Update bones_framework - fix desync on net correction at max prediction

- Cargo.lock
> chore(deps): Update bones (get net fps fix)

- Cargo.lock
- src/main.rs
Update bones version + fix missing preload setting
> chore: Update bones renderer

- .gitattributes
> fix: Force git attributes unix line endings

- .gitattributes
Should address at least part if not all of the issues with the current .gitattributes
> chore: Update git attributes to have explicit inclusion/exclusion

- src/input.rs
Follow-up to #1023, partially reverting it as there is a simpler fix, and fixing the remaining bugs.
> fix: gamepad inputs

- Cargo.lock
> feat: upgrade bones

- src/ui/map_select.rs
> fix(ui): scroll to focused button in map select
