Cargo.lock, Cargo.toml
Hello,
Recently I came across your project, tried it out and it's very fun :fish:
One thing I realized is that the binary was named "fishgame" and I thought this was supposed to be consistent with the project/organization name. So this PR basically renames the Rust crate to "fishfight". Feel free to close the PR if the initial naming was intentional.
Thank you!
=> Rename crate to `fishfight`

src/items.rs, src/items/turtle_shell.rs
reimplemantation of the old code functionality, adapted to use the scene::add_node and spawn functions. The shell stops two shots from the back as it previously did.
=> Turtle Shell reimplementation

src/main.rs
I thought it would be more appropriate to rename the window to match the project's name.
=> Set the window title to "FishFight"

src/items.rs, src/items/mines.rs
Resolve #99.
* Checked out from 3ba21b6185114a5c69c791c12fc1e0884bfcb102 — the last
commit where this weapon existed.
* Uses work in progress from #113 for explosive projectiles. Since that work is behind `main` by a few commits, I simply copied the files I needed. This patch will become half its current size once #113 is merged.
=> Put mines back.

src/gui.rs, src/main.rs
This PR makes it possible to specify the "assets/" directory at runtime by checking the presence of `FISHFIGHT_ASSETS` environment variable.
Closes #132
=> Support specifying the assets directory at runtime

src/main.rs
See #132
This PR updates the asset location for the Jellyfish implementation thus makes it specifiable at runtime with using `FISHFIGHT_ASSETS` environment variable.
=> Use dynamic asset location for the jellyfish asset

.github/workflows/validation.yml, assets/items/cannon.schema.json, assets/maps.schema.json, assets/textures.schema.json, scripts/validate_json.sh
Closes #187
This PR adds the initial implementation for validating JSON files using schemas. There are a few key points:
- As mentioned in `validate_json.sh` script, schemas can be added and validated in 2 ways:
- You can add the corresponding schema for a JSON file, such as `file.schema.json`
- Or you add a _common_ schema file named `schema.json` in a directory and it is used for validating all of the JSON files in that directory.
- Current implementation only supports [JSON Draft-07 Schemas](https://json-schema.org/draft-07/json-schema-release-notes.html) and they can be written by hand or generated using tools like [this site](https://extendsclass.com/json-schema-validator.html).
- I only added 3 generated schema files in this PR but we should probably add more schema files for …
=> Add schema validation for JSON files

src/editor/gui/windows/background_properties.rs, src/editor/gui/windows/load_map.rs, src/gui/mod.rs, src/gui/style.rs
This enables loading of maps directly from the editor menu so you won't have to exit to main menu every time this is needed
=> Map loading from editor menu

Cargo.lock, Cargo.toml, src/particles.rs, src/resources.rs
I renamed the `macroquad-particles` fork and published it on `crates.io` and this updates our dependencies accordingly
=> Update ff-particles dependency

src/components/animation_player.rs, src/components/particle_controller.rs, src/effects/active/projectiles.rs, src/json/helpers.rs, src/json/mod.rs
This adds `should_autostart` to `ParticleControllerParams` so that effects can be started automatically, once the controller is instantiated
=> Projectile particle fix

book/src/editor.md, src/editor/camera.rs, src/editor/input.rs, src/editor/mod.rs, src/editor/tools/eraser.rs, src/editor/tools/mod.rs, src/editor/tools/placement.rs, src/gui/main_menu.rs
This adds the following to the editor:
- Map bounds and tile grid can be toggled by pressing `G`
- Double clicking an object will now open its properties
- Selected objects can be moved by drag and drop
- Grid snap when moving objects by dragging can be toggled by pressing `ctrl + G`
- Save map by pressing `ctrl + S`, save as by pressing `ctrl + shift + S` and load map by pressing `ctrl + L`
=> Editor polishing

src/editor/actions.rs, src/editor/gui/toolbars/layer_list.rs, src/editor/gui/windows/mod.rs, src/editor/gui/windows/tile_properties.rs, src/editor/mod.rs, src/game/scene.rs, src/gui/mod.rs, src/gui/style.rs
This adds tile selection and a tile attributes window, accessible by double clicking a tile.
It will only give you the possibility to set a tile as jumpthrough, for now, but in the future we will probably add more attributes to be set on tile level.
This should be the last missing feature before the editor offers a complete workflow...
=> Tile attributes

.github/workflows/release.yml
This PR tackles the following issues about the release workflow:
- `assets/` directory is now included in release artifacts (related to #296)
- artifacts are now named as `fishfight-<version>-<target>.<ext>`
- fixes #297 in 49fd53b5ee4adada9c6ac4b1d80dad8c831852ad
=> Improve automated releases

Cargo.lock, Cargo.toml
See #309
I will submit another PR shortly for updating README.md about this.
=> Remove bundled-sdl2 feature from fishsticks dependency

src/gui/credits.rs, src/main.rs
When `assets/` directory is located outside the current path, going to the credits screen crashes the game:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FileError { kind: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" }), path: "./assets/ui/AnonymousPro-Regular.ttf" }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.13/src/text.rs:239:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR fixes this issue by refactoring the `show_game_credits` function to respect any custom assets directory specified by `FISHFIGHT_ASSETS` environment variable.
=> Support loading the credits font from a custom assets directory

src/ecs.rs, src/editor/gui/combobox.rs, src/editor/gui/mod.rs, src/editor/gui/toolbars/mod.rs, src/editor/gui/toolbars/tool_selector.rs, src/game/mod.rs, src/gui/select_character.rs, src/math.rs, src/network/api.rs, src/physics/body.rs, src/physics/mod.rs, src/player/character.rs, src/player/state.rs, src/sprite/mod.rs
This tweaks gravity, adds terminal velocity and makes gravity canceled if jump is held for a certain amount of frames, after jump is initiated.
This can still be tweaked, probably, so feel free to play around with the parameters:
`crate::physics::GRAVITY` - gravity
`crate::physics::TERMINAL_VELOCITY` - terminal velocity
`crate::player::character::PlayerCharacterMetadata::DEFAULT_JUMP_FORCE` - default jump force
`crate::player::state::JUMP_FRAME_COUNT` - max number of frames without gravity
=> Fix gravity and jump

src/effects/active/projectiles.rs, src/effects/active/triggered.rs, src/game/mod.rs, src/items/mod.rs, src/map/decoration.rs, src/map/sproinger.rs, src/player/inventory.rs, src/player/mod.rs, src/sprite/animated.rs, src/sprite/mod.rs
This adds a `DrawOrder` component that must be added to all drawables, which determines where in the draw order it is drawn.
For items, draw order is handled by having them use a set constant draw order when on the ground and the players draw order + 1, when equipped.
The players draw order is its index + 1, multiplied by 10, so there is room to sort equipped items more precisely, if we want to.
In the future we might want to remove the requirement of a`DrawOrder` component to have something draw and iterate through drawables without a set draw order and either draw them before or after all the ordered draws.
Also, this currently queries for all entities with a `DrawOrder` component and then queries for the possible drawable component types in a series of if/else statements. This might …
=> Fix draw order

assets/items/blunderbass.json, assets/items/blunderbuss.json, assets/items/cannon.json, assets/items/crate.json, assets/items/grenades.json, assets/items/kick_bomb.json, assets/items/machine_gun.json, assets/items/mines.json, assets/items/musket.json, assets/items/sniper_rifle.json, assets/items/sword.json, assets/items/turtle_shell.json, src/effects/active/mod.rs, src/effects/active/projectiles.rs, src/effects/passive/mod.rs, src/effects/passive/turtle_shell.rs, src/game/mod.rs, src/items/mod.rs, src/items/weapon.rs, src/main.rs, src/player/events.rs, src/player/inventory.rs, src/player/mod.rs, src/player/state.rs
This adds passive effects back, after the ECS refactor. It also contains an example implementation of an item using passive effects (turtle shell)
=> Reimplement passive effects

assets/items/sword.json, src/effects/active/mod.rs, src/game/mod.rs, src/player/state.rs
This adds debug draw for active effect colliders (CircleCollider and RectCollider), removes segments from CircleCollider and replaces segmented CircleCollider with a RectCollider on sword
=> Add debug draw for collider effects and remove segmets from circle collider

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml, README.md
This PR does the following changes:
- `bundled-sdl2` feature is now enabled for `fishsticks` dependency (required for the release workflow)
- same targets are used for both CI (`ci.yml`) and CD (`release.yml`) workflows (closes #127 )
And now we should be all set for the upcoming release!
=> Update CI/CD workflows

network-core/src/error.rs, src/error.rs
Moved `ErrorKind` back to the main codebase and created a new one for network-core
=> Small fix to error types

network-core/src/lib.rs, src/effects/active/mod.rs, src/effects/active/projectiles.rs, src/effects/active/triggered.rs, src/effects/passive/turtle_shell.rs, src/items.rs, src/player/animation.rs, src/player/events.rs, src/player/inventory.rs, src/player/mod.rs, src/player/state.rs
This removes the `PlayerState` component and moves most of its content to the `Player` component, so that the name `PlayerState` can be used for a state enum (held by the `Player` component) in stead.
=> Some cleanup of player state

.gitignore, Cargo.toml, core/src/network/api.rs, core/src/network/event.rs, core/src/network/mod.rs, mods/active_mods.json, mods/test_mod_one/fishfight_mod.json, mods/test_mod_two/fishfight_mod.json, src/editor/gui/windows/create_map.rs, src/editor/gui/windows/save_map.rs, src/editor/mod.rs, src/gui/create_map.rs, src/main.rs, src/network.rs, src/resources.rs
This PR adds mods to Fish Fight.
Currently, only data mods are allowed and they will currently **extend** the core resources (in the future we will add a replace option, for when creating total conversion mods). This means that a mods resources will be added to `Resources`, or overwrite existing resources, if ids are the same.
The `mods` directory holds two example mods that show how to create a mod and how dependencies work. These examples hold no actual content but this is added just like when adding to the `assets` dir, using the same resource file names and the same folder.
Mods are loaded in order, according to the order given in `active_mods.json`
All resources that are loaded dynamically are supported in mods:
- decoration (`decoration.json`)
- images (`images.json`)
- items …
=> Mod loading

.github/workflows/release.yml
This PR updates release workflow for creating release archives that do not involve JSON schemas since they are not needed at runtime.
=> Remove schema files from release assets

src/gui/main_menu.rs, src/gui/select_character.rs, src/resources.rs
This stores player characters in a map in stead of a vec (in `Resources`), so that it is more consistent with the other resources (and allows overwriting in mods).
It also disables the network game button in main menu for release builds (as networking makes the game crash to desktop atm)
=> Store player characters in a hash map in stead of a vec

.github/workflows/release.yml
This PR updates the release workflow to include `mods/` folder in resulting archives.
=> Include mods folder in release archives

src/main.rs, src/resources.rs
This PR removes `GAME_VERSION` constant and uses `env!("CARGO_PKG_VERSION")` for comparing the current version of the game with the required version.
=> Use the package version as game version

PACKAGING.md
SDL2 is removed and `libudev` is required for building FF now.
=> Update PACKAGING.md about build dependencies

config.toml, core/Cargo.toml, core/src/config.rs, core/src/input/mapping.rs, core/src/input/mod.rs, core/src/lib.rs, src/main.rs
This removes the `Resolution` type and add its members, as well as other window-related stuff, to a new `WindowConfig` type
=> Add WindowConfig type to Config

.github/workflows/ci.yml
This PR disables debug mode builds until `windows-latest` runners are stable again.
=> Disable debug builds

.github/workflows/release.yml
This PR updates release workflow to include the `licenses` folder in release archives.
=> Include licenses folder in release archives

Cargo.lock, Cargo.toml, RELEASE.md, core/Cargo.toml
=> Prepare for v0.4.2 release

src/map/sproinger.rs, src/player/character.rs, src/player/mod.rs
Made a adjustments to default character gravity and jump values as i was asked
=> Tweak character jump

Cargo.lock, core/Cargo.toml, core/src/input/mapping.rs, core/src/input/mod.rs
This PR updates [fishsticks](https://github.com/fishfight/fishsticks) dependency to the latest version (`0.2.1`) and fixes the compilation errors that occurred due to this change.
=> Update fishsticks dependency

src/main.rs
Avoid entering an endless loop when clicking the "Reload Resources" button.
Eventually we might want a progress bar or something, because the UI will freeze while the assets are being loaded, but that's not a big deal and not something that needs to be done now.
=> Fix Reload Resources Button

.github/workflows/ci.yml, .github/workflows/release.yml, rust-toolchain.toml
Build is failing on the `main` branch due to https://github.com/rust-lang/rust/issues/93706
```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
--> core/src/math/size.rs:16:6
|
16 | impl<T: Num + Copy> Size<T> {
|      ^
17 |     pub const fn new(width: T, height: T) -> Self {
|     --------------------------------------------- function declared as const here
|
= note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
For more information about this error, try `rustc --explain E0658`.
error: could not compile `fishfight-core` due to previous error
Error: Process completed with exit code 101.
```
This PR updates the workflows and adds a Rust toolchain configuration to use nightly channel until `const_fn_trait_bound` is …
=> Switch to Rust nightly for builds

src/editor/mod.rs
At non-default zoom levels, the drop placement of objects on the map
change unexpectedly as soon as releasing the mouse button. This fixes
that.
=> Fix Drag and Drop Object Placement

book/src/multiplayer.md
Just noticed some small typos while reading through
=> Fix typos in `multiplayer.md`

src/editor/actions.rs, src/gui/select_map.rs, src/json/map/tiled.rs, src/map/mod.rs
Hello I enjoyed the game so I decided to check if some easy pick were possible, saw that some cargo clippy were possible.
Thanks for the game :purple_heart: !
=> clippy: fix unnecessary casting

src/game/camera.rs
Rational:
```
warning: clamp-like pattern without using clamp function
--> src/game/camera.rs:68:17
|
68 |                 rect.x.max(min.x).min(max.x),
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with clamp: `rect.x.clamp(min.x, max.x)`
|
= note: clamp will panic if max < min, min.is_nan(), or max.is_nan()
= note: clamp returns NaN if the input is NaN
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_clamp
= note: `#[warn(clippy::manual_clamp)]` on by default
warning: clamp-like pattern without using clamp function
--> src/game/camera.rs:69:17
|
69 |                 rect.y.max(min.y).min(max.y),
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with clamp: `rect.y.clamp(min.y, max.y)`
|
= note: clamp will …
```
=> clippy: use clamp in camera.rs

src/json/map/mod.rs
rationale:
```
warning: iterating on a map's values
--> src/json/map/mod.rs:94:24
|
94 |           let tilesets = other
|  ________________________^
95 | |             .tilesets
96 | |             .into_iter()
97 | |             .map(|(_, tileset)| tileset)
| |________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_kv_map
= note: `#[warn(clippy::iter_kv_map)]` on by default
help: try
|
94 ~         let tilesets = other
95 +             .tilesets.into_values()
|
```
=> clippy: use into_values in mod.rs

src/resources.rs
Rationale:
```
warning: used consecutive `str::replace` call
--> src/resources.rs:499:10
|
499 |     name.replace(' ', "_").replace('.', "_").to_lowercase()
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `replace([' ', '.'], "_")`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_str_replace
= note: `#[warn(clippy::collapsible_str_replace)]` on by default
```
=> clippy: use replace with arg-list

assets/map/elements/item/sword/sword.ts
The sword damage regions weren't spawning correctly after adding the bombs.
=> Fix Sword Damage Region Spawning

src/map/elements/sword.rs, src/player/state/states/idle.rs, src/player/state/states/midair.rs, src/player/state/states/walk.rs
Now you can't steal items that are being held. Also an extra little fix for a sword animation panic.
=> Sword fixes

src/player/state/states/idle.rs, src/player/state/states/midair.rs, src/player/state/states/walk.rs
This is based on the guess that the desync came from the lack of determinism in the scenario when you grab an item while touching multiple items, and it isn't necessarily specified which one you pick up.
=> Attempt to Fix Multiplayer Desync

src/config.rs, src/session.rs, src/ui/editor.rs
=> Fix Editor Not Displaying Map Elements

Cargo.lock, Cargo.toml, src/main.rs, src/map/elements/grenade.rs, src/map/elements/player_spawner.rs, src/map/elements/sproinger.rs, src/map/elements/sword.rs, src/networking.rs, src/networking/proto.rs, src/player/input.rs, src/prelude.rs, src/session.rs, src/ui/editor.rs, src/ui/main_menu.rs, src/ui/main_menu/map_select.rs, src/ui/main_menu/matchmaking.rs, src/ui/pause_menu.rs, src/utils.rs
Reset and map selection buttons won't sync over the network for now.
=> Sync Network Pause State

assets/map/levels/level1.map.yaml, assets/map/levels/level2.map.yaml, assets/map/levels/level3.map.yaml, assets/map/levels/level4.map.yaml, src/camera.rs, src/map.rs, src/map/elements.rs, src/map/elements/grenade.rs, src/map/elements/sword.rs, src/ui/main_menu/map_select.rs
=> Handle out of bounds

Cargo.lock, Cargo.toml, src/animation.rs, src/camera.rs, src/damage.rs, src/lifetime.rs, src/main.rs, src/map.rs, src/map/elements/decoration.rs, src/map/elements/grenade.rs, src/map/elements/player_spawner.rs, src/map/elements/sproinger.rs, src/map/elements/sword.rs, src/player.rs, src/player/input.rs, src/schedule.rs, src/session.rs, src/utils/event.rs
This fixes a network desync issue with grabbing overlapping items.
bors merge
=> Make System Execution Order More Deterministic

assets/map/levels/level1.map.yaml, assets/map/levels/level2.map.yaml, assets/map/levels/level3.map.yaml, assets/map/levels/level4.map.yaml, src/physics.rs
=> Item placement

assets/player/skins/catty/catty.player.yaml, assets/player/skins/fishy/fishy.player.yaml, assets/player/skins/lionfishy/lionfishy.player.yaml, assets/player/skins/orcy/orcy.player.yaml, assets/player/skins/pescy/pescy.player.yaml, assets/player/skins/sharky/sharky.player.yaml, src/config.rs, src/debug.rs, src/metadata/player.rs, src/physics.rs, src/player/state/states/midair.rs, src/ui/debug_tools.rs
=> Slow Falling & Default-enable Debug Tools

.github/workflows/docs.yml
Tells cargo to build the docs for the entire workspace. Hopefully that fixes the broken links to other crates in the workspace.
bors merge
=> fix(docs): Try to Fix Broken Docs Links In CI

src/networking.md
- Mention how we send GGRS's unreliable messages.
- Mention using the `Rollback` component for query sorting.
bors merge
=> fix(docs): Add Notes to Networking Doc

Cargo.lock, Cargo.toml, crates/matchmaker/Cargo.toml
otherwise `cargo vendor` fails
=> matchmaker: switch postcard dependency from crate to git

src/ui/main_menu/settings/controls.rs
This adds support for mouse bindings in the settings menu. It also allows to use them in-game. I changed `BindingKind::Keyboard` to `BindingKind::KeyboardMouse` for clarity (both go together).
=> Add support for mouse inputs in settings

.github/workflows/docs.yml
Hopefully this will improve the docs build time in CI which
seems to be longer than it should be.
=> ci: use independent cache for docs build in CI.

core/src/map.rs
Fixed a bug noticed by @SirGiraffey where tiles with
empty colliders would load as solid colliders when the
map was reloaded.
=> fix: fix empty map tile collisions loading as solid tiles.

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml
This updates each CI workflow to use it's own cache key. It appears that trying to re-use caches across workflows doesn't work properly.
This also removes the caching from the release workflow which will only run for nightly releases and tagged releases so we don't need to waste the cache space when we can afford to just wait for the builds.
=> ci: update CI caches.

core/src/player/state/states/crouch.rs
The sliding animation commit accidentally broke the crouch animation.
=> fix: fix crouch animation not playing.

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/web-demo.yml
GitHub changed the rules for CI caches at some point so that they can not be changed after being created. This takes that into account and uses a different cache for different platform + Cargo.lock combinations.
=> ci: adjust CI caches to avoid cache misses.

core/src/bullet.rs, core/src/elements/musket.rs
This fixes #715. Issue suggested that what should be done is adding owner to damage region (as is done in case of sword), however it seems that bullet does not use those regions so I simply add entity marker to bullet object and filter out all collisions with this entity.
=> fix: prevent bullet from killing shooter.

.github/workflows/merge-group-commit-lint.yml
This should fix the issue where the merge group was not stopped if the commit lint failed.
=> ci: make sure commit lint action can be required in merge group.

assets/locales/en-US/editor.ftl, core/src/metadata/element.rs
Remove unused translations and remove unused field from kick bomb.
Fixes: #713
=> fix: fix startup warnings.

Cargo.lock, core/src/attachment.rs, core/src/debug.rs, core/src/elements/kick_bomb.rs, core/src/elements/stomp_boots.rs, core/src/globals.rs, core/src/item.rs, core/src/lib.rs, core/src/lifetime.rs, core/src/metadata/common.rs, core/src/player.rs, core/src/prelude.rs, core/src/utils.rs, core/src/utils/easing.rs, core/src/utils/math.rs, core/src/utils/rect.rs, src/metadata.rs
- If invincibility is active, have the player breathe slightly with their alpha
https://user-images.githubusercontent.com/9278174/227737396-c9e94623-1fb1-4872-a358-d47b1e078be7.mp4
=> feat: sync sprite color and attachments.

Cargo.lock, core/src/elements/grenade.rs
updated grenade.rs to use bones timer instead of manually setting time to 4.0 seconds
attempts to resolve #739
=> refactor: update grenade.rs to use bones timer.

assets/elements/item/kick_bomb/kick_bomb.element.yaml, core/src/elements/kick_bomb.rs, core/src/metadata/element.rs
Added bomb timer to kick_bomb.rs instead of manually setting the time. 
Fixes: #741
=> refactor: use bones timer for kick bomb fuse and arm delay.

assets/elements/item/kick_bomb/kick_bomb.element.yaml
Apparently serde humantime doesn't support floating points.
=> fix: fix kick-bomb time parsing in element YAML.

src/audio.rs
The music tracks were not set to play on looped mode for menus such as the character selection or home menu. This would cause the game to crash when the track had finished and the transition to another menu page caused the system to try and stop the currently playing song ( which was no longer playing ).
=> fix: fix crash related to menu music not looping.

src/networking.rs, src/networking/lan.rs, src/ui/main_menu/network_game.rs
Previously the peers were only connecting to the matchmaker without coordinating to connect to each-other and be able to start the match.
Fixes: #749
=> fix: fix 3 and 4 player LAN games.

src/networking.rs, src/networking/lan.rs, src/session.rs, src/ui/main_menu/network_game.rs
This renames `LanSessionRunner` to `GgrsSessionRunner` and moves it to the `networking` module to prepare for making the `GgrsSessionRunner` agnostic to LAN or online games with a new network socket trait.
=> style: rename and move LAN session runner to prepare for online matchmaking.

src/networking/lan.rs
This greatly improves the experience at the cost of greater bandwidth, which in bad network conditions might make a worse experience. We may have to experiment to find the best value.
This brings the frame rate up from 45 to 54 frames-per-second for LAN games.
=> feat: increase LAN game frame rate.

src/networking.rs, src/networking/lan.rs, src/session.rs, src/ui/main_menu/map_select.rs, src/ui/main_menu/network_game.rs, src/ui/main_menu/player_select.rs
=> feat: allow selecting player and map in LAN games.

core/src/editor.rs, core/src/elements.rs, core/src/elements/fish_school.rs
The rendered fish school (and the subsequent fish) will now be removed when the parent element is removed (right-click element and choose "Delete Element").
=> fix: fish school removed from editor on element deletion

Cargo.lock
mimalloc 0.1.35 is causing build failures on some architectures.
https://github.com/purpleprotocol/mimalloc_rust/issues/92
=> build: upgrade mimalloc to 0.1.36.

core/src/editor.rs, core/src/elements.rs, core/src/elements/crab.rs, core/src/elements/crate_item.rs, core/src/elements/fish_school.rs, core/src/elements/grenade.rs, core/src/elements/kick_bomb.rs, core/src/elements/mine.rs, core/src/elements/musket.rs, core/src/elements/snail.rs, core/src/elements/stomp_boots.rs, core/src/elements/sword.rs, core/src/elements/urchin.rs
All elements that act as a spawner (except for the fish school since the spawner acts as the parent element holding the inner fish elements) now have a Spawner component that will be discovered during the "delete element" process.
I also updated the ElementKillCallback ulid string since I just created it manually in the previous ticket and only recently learned of a way to generate a true random ulid string.
We should consider refactoring the fish school spawner to properly behave like a spawner containing entities.
=> fix: implement kill callback for all rendered elements

src/ui/main_menu.rs, src/ui/main_menu/settings.rs
Moves the code for the `SettingsTab` struct to the settings.rs file, where the struct itself is.
Hopefully resolves #778.
=> refactor: moved SettingsTab to settings.rs

Cargo.lock, Cargo.toml
closes #614 
Removes transitive bevy_pbr dependency as found with help of `cargo tree -i bevy_pbr `.
=> build: remove transitive bevy_pbr dependency.

Cargo.lock, Cargo.toml, core/Cargo.toml
Also updates to use two digit version numbers for most crates.
=> build: cargo update and remove unused deps.

core/src/player.rs, core/src/player/state/states/walk.rs
- Adds random pauses to AI movement.
- Slows AI movement down.
- Makes AI get closer to player before swinging sword.
- Also allows players to move slower by tilting the stick less.
Resolves #787
=> fix: make AI less effective so they are more fun to play against.

.github/workflows/release.yml, Cross.toml
Closes #788
Tested here: https://github.com/orhun/FishFight/actions/runs/5204576645 
Unfortunately, `cross` doesn't support wildcard for targets so there is a bit of code duplication in the config. See https://github.com/cross-rs/cross/issues/1244
=> chore(release): add ARM64 linux builds

docs/rustdoc-mermaid-head.html, src/README.md, src/assets.rs, src/assets/asset_handle.rs, src/audio.rs, src/bevy_states.rs, src/camera.rs, src/config.rs, src/main.rs, src/prelude.rs, src/session.rs
- improved main page and several modules.
- also move state enums into their own module for readability.
Works on: #479
=> docs: add more Jumpy API documentation.

src/session.rs
fixes #722 
I'm still getting familiar with the code, but it looks like what's happening is that when you press the Grab/Drop key on Keyboard 2, the input sometimes makes the AI player drop the sword and when it has enough velocity it gets insta-killed by collision detection (this I think is related to #714). I was able to reproduce this issue in a local game only.
After some digging, I found that this seems to be caused the session's input being propagated to all the player inputs including the AIs in a local session (when `network_player_idx.is_some()`). Removing the condition skips the loop for AI players locally and still works in a network game, where each local player has `player_idx = 0`.
=> fix: input controls being applied to ai players.

core/src/metadata/common.rs
Makes sure the serialization format for colors matched the deserialization format.
This fixes an issue where saved user maps would fail to load.
=> fix: fix color serialization breaking map saving.

src/networking/lan.rs, src/ui/main_menu/network_game.rs
hi, I've been going through some networking code and found that the coupling with UI made it harder to follow it. This PR refactors the LAN related logic into its module with no changes in the functionality.
=> refactor: decouple LAN logic from UI for network_game

assets/locales/en-US/debug-tools.ftl, src/ui/debug_tools.rs
This fixes the way that the profile window check box was toggling the frame-time diagnostics, instead of the profiler window.
Also improves organization of the window by adding a couple headings for the different kinds of toggles.
=> fix: fix debug tools window checkbox for profile window.

Cargo.lock, Cargo.toml, core/Cargo.toml
Fix #831, we are using incompatible puffin / puffin-egui versions.
We updated puffin to 0.16, but did not upgrade puffin_egui to 0.22 (these versions were bumped together). We likely did not upgrade puffin_egui because this causes a compilation error, as bevy_egui is still using dep egui 0.21 (while puffin_egui is at 0.22), types mismatch.
Downgrading puffin to 0.15 fixes it. Can upgrade puffin crates once bevy_egui has a release with egui 0.22.
Additionally, fixes a panic opening profiler in wasm due to missing web feature.
=> fix:  Fix puffin profiler not showing anything

scripts/build-web.sh
/bin/env does not exist on the system I am currently using (macOS 12.5). 
It seems to me /bin/usr/env is probably more common - that said I really hope this change wouldn't create the opposite problem for others. (Though could always do #!/bin/bash). 
Probably worth addressing one way or another so script does not require local modification to build wasm.
=> fix: change /bin/env to /usr/bin/env in build-web.sh.

Cargo.lock, Cargo.toml, src/logs.rs, src/main.rs, src/puffin_tracing.rs
Adds feature flag "profiling-full" to jumpy that allows profiling bevy in puffin. (https://github.com/fishfolk/jumpy/issues/837)
Bevy profiling is implemented with tracing spans, this change adds a layer creating puffin scopes from spans, based off of work from here: https://github.com/mvlabat/bevy_puffin. Includes some custom field formatting so we don't get debug formatting in puffin scopes, the default was a bit hard to read.
This is behind a feature flag as it requires enabling tracing in bevy, which causes significant performance issues in wasm. The profile scopes are a bit harder to sift through as there is a lot more information, however it should be helpful for getting a more detailed understanding of what is happening. 
Example screenshot below, hard to get all the interesting …
=> feat(profiling): allow puffin to capture tracing spans for profiling.

src/loading.rs
Maybe I should've opened a bug for this (still can if we want one), but I think I identified the issue.
I've crashed  a handful of times in loading.rs, (GameLoader), here:
```rust
// Load player hat atlase egui handles
for hat_handle in &core.player_hats {
let hat_meta = self.hat_assets.get(&hat_handle.get_bevy_handle()).unwrap();
let path = hat_meta.atlas.path.clone()
```
I believe this is because we were not waiting for asset to be loaded (checking if the hat asset had been loading in core_assets_loaded), so some of the time if not yet loaded by bevy would fail to get asset.
=> fix: fixes occasional crash in loading while accessing hats.

Cargo.lock, Cargo.toml, src/debug.rs, src/logs.rs, src/main.rs, src/profiling.rs, src/puffin_tracing.rs
Renamed PuffinScopeFormatter to ProfilingScopeFormatter, moved into profiling.rs. Enables support for Tracy under profiling-full feature.
Shouldn't impact puffin at all, just opening PR as I have been enjoying tracy and wanted to make the work available for others.
=> refactor(profiling): support Tracy profiler for tracing spans. 

core/src/physics.rs
While doing some testing, I changed crate::FPS to be 30 instead of 60, this caused everything to move half as fast.
I do not believe the time needs to be relative to FPS here. The time used is fixed value computed based on timestep. Time resource used here is advanced based on crate::FPS and NETWORK_FRAME_RATE_FACTOR (in networked game, or just crate::FPS in offline). This means it is already adjusted based on frequency of updates. Due to this, objects already move a consistent speed when using different frame rates.
Changing this to scale by 60 makes velocities consistent regardless of crate::FPS value, we are keeping scale by constant 60 to avoid changing velocities everywhere else.
=> fix(time_step): Fix time_factor causing velocity to be dependent on crate::FPS.

assets/locales/en-US/debug-tools.ftl, src/networking.rs, src/networking/debug.rs, src/ui/debug_tools.rs
This adds a menu on F6 for visualizing state of network prediction. Tool is disabled in wasm as networking is not available.
It features a bar graph for each frame showing how many frames client is predicted from last confirmed frame. Frames in which we froze waiting for network input are highlighted in yellow. That's pretty much it right now - def more that can be added here, but I have found it a useful starting point.
=> feat: Add visual debug tool for network prediction

assets/locales/en-US/debug-tools.ftl, src/networking.rs, src/networking/debug.rs
GGRS has api exposing network stats per remote player, this change collects this data and displays in network debug tool.
This shows current ping, send queue length, estimated frames ahead/behind this player is from local player, and kb/s being sent.
=> feat(network-debug): Network debug tool shows ggrs network stats per player

core/src/physics.rs, core/src/player.rs
So the stat shown in #847 wasn't too representative of the costs as I had removed the critters and such.
This change checks if kinematic has moved since last update, and only tries shove out if it has moved. (If hasn't moved, either isn't colliding and doesn't need shove out, or is stuck and another shove out will yield same results and remain stuck).
This removed about 1ms from update_kinematic_bodies.
Would like to leave #847 open, I am aiming to also skip the fallthrough collision check if hasn't moved, however there is additional complexity here related to fall_through bool, and I don't want to break stuff so that will come later. If we can skip that - should be able to get this function to almost only spend time on moving objects and save even more.
=> feat: Skip update_kinematic_bodies shove loop and check falling branch if object has not moved since last update.

src/networking.rs
increase max prediction window to 10, seems to remove freezes due to latency in my testing, we can proceed to tune further once we have data points. Concern is rollbacks max-cost may increase, in practice I have not hit rewinds above 8 frames anyway.
=> fix(prediction): Increase max prediction window to 10.

src/main.rs
Jumpy will now read the `JUMPY_ASSETS` and `JUMPY_ASSET_PACKS` environment variables.
=> feat: allow setting asset and asset pack dirs with environment variables.

src/core/physics.rs
I seem to have set the update of saved positions used to determine if kinematic has moved in the wrong spot, ended up in a situation in which AI thinks it had not moved, but was inching down by -0.1 each frame, sinking into ground.
I was able to repro fairly consistently and feeling pretty confident this should fix the AI sinking into ground described in #882. (Though I do not believe this is related to the losing control of player bit).
EDIT:  #853 (objects stuck in walls) also appears to be resolved by this fix.
=> fix(character_movement): Fix sleeping kinematic / has_moved optimization causing AI to sink into ground

src/input.rs
Whenever the same key or button had multiple input events that happend in the same frame, only the first event would be honored, leading to issues where the "release" events were not being picked up and buttons would get stuck in a "pressed" state.
Resolves: #882
=> fix: fix drop of player inputs for multiple button events per frame.

Cargo.lock
This was accidentally missed from the latest commit.
=> chore: update Cargo.lock to include correct crate version.

Cargo.lock, Cargo.toml, build.rs, src/ui/main_menu.rs
=> chore(build): use shadow-rs for build info

Cargo.lock, Cargo.toml
The previous release had not included the update to the Cargo.lock, so this makes another release to fix that.
=> chore(release): bump crate version.

.github/workflows/ci.yml
might help catching outdated Cargo.lock
=> chore(ci): run clippy with `--locked` flag

src/core/elements/kick_bomb.rs
While working on the jellyfish I noticed that the kick bomb wasn't working.
When spawned they didn't get an `ElementHandle` component (or `MapElementHydrated`). Without an element handle the `update_idle_kick_bombs` system always skipped over them, preventing them from being used.
=> fix: Kick Bomb can't be used

src/core/elements/crate_item.rs, src/core/elements/grenade.rs, src/core/elements/jellyfish.rs, src/core/elements/kick_bomb.rs, src/core/elements/mine.rs, src/core/elements/musket.rs, src/core/elements/stomp_boots.rs, src/core/elements/sword.rs, src/core/item.rs, src/core/player.rs, src/core/player/state/states/drive_jellyfish.rs
I noticed that in many places in the codebase, it's necessary to find the inventory that contains some item (usually to get the player entity), if any exists, from the `PlayerInventories` system param. This simply adds a helper method `find_item` that does the `.iter().find_map(...)` that is duplicated in many places.
There is also some minor cleanup regarding `ComponentStore::remove`.
=> feat: Add a find helper method to `PlayerInventories`

src/core.rs, src/core/camera.rs, src/core/elements/flappy_jellyfish.rs, src/core/elements/jellyfish.rs, src/core/player.rs, src/core/player/state/states/drive_jellyfish.rs
Take 2 🎬 this is the second iteration of the Jellyfish item, based on Duck Game's [RC Controller](https://duckgame.fandom.com/wiki/RC_Controller).
More tweaks may come in follow-up PRs
- The camera follows any entity with the new `CameraSubject` component
- Entity must also have a `Transform` and `KinematicBody` to work properly
- The flappy jellyfish collides with solids
- The flappy is now much more jerky and overly responsive to user input, I may add acceleration to the left/right movement so that it floats around more to give it a more natural feel
- Control the jellyfish like Duck Game's RC Controller
- The flappy is tied to the jellyfish hat, not the player
- If the driver dies/drops the jellyfish the flappy doesn't explode, another player can pick it up and take control
- Despawn & …
=> feat: Jellyfish v2

.github/workflows/web-demo.yml, Cargo.lock, Cargo.toml, src/core.rs, src/core/input.rs, src/core/player.rs, src/input.rs, src/sessions.rs, src/settings.rs, src/ui.rs, src/ui/main_menu.rs, src/ui/main_menu/map_select.rs, src/ui/main_menu/network_game.rs, src/ui/main_menu/player_select.rs, src/ui/map_select.rs, src/ui/network_game.rs, src/ui/pause_menu.rs
This adds menu + gameplay for online matches back into Jumpy. Some work left to do, but I think this is a good checkpoint, online matches work, lan is still disabled (this is up next).
TODO:
- Lan
- Cleanup menu code a bit more
- Pause menu (right now disabled, need to figure out how to do this without disabling session as I think that causes issues)
=> feat(networking): Re-implement networking from bones + re-add online matches

assets/elements/item/kick_bomb/kick_bomb.yaml, src/core/elements/kick_bomb.rs
Closes #720
- Shorter fuse time: 4s, same as grenade
- Less bouncy
- Explodes on the third kick from a player
=> fix: kick bomb randomness

src/core/elements/slippery_seaweed.rs, src/core/player/state/states/crouch.rs
Closes #910
This was more simple than I expected. When a sliding player collides with something and stops moving, the transform adjustment to stand up didn't take into account the direction the player is facing.
https://github.com/fishfolk/jumpy/assets/25290530/aecf7cf4-72ef-427b-8f16-73000f43ad5f
=> fix: sliding collisions

Cargo.lock, src/core/physics/collisions.rs, src/debug.rs
Install the bones network debug egui plugin / add a button to open it from debug window.
Companion PR to https://github.com/fishfolk/bones/pull/345
=> feat(network-diagnostics): Install bones network debug window

.gitignore, PACKAGING.md, steam/launch_scripts/linux/jumpy.sh, steam/launch_scripts/linux/jumpy_desktop.sh, steam/package_steam.sh
Add a steam_package.sh script that pulls releases from github, rezips as .zip such that they can be uploaded to steamworks for respective platforms.
For linux, we also install some launch scripts. There's logic here to fix #904. Isn't pretty but seems to work, scaling is correct in steam deck game mode + desktop mode. Should not impact other linux platforms. 
Need to test again with steam deck with external display, but I think this should work based on last I was exploring solutions to #904.
=> build(steam): Steam packaging utility + linux launch scripts

assets/elements/environment/crab/crab.yaml, assets/elements/environment/snail/snail.yaml, assets/elements/environment/sproinger/sproinger.yaml, assets/elements/environment/urchin/urchin.yaml, assets/elements/item/crate/crate.yaml, assets/elements/item/grenade/grenade.yaml, assets/elements/item/jellyfish/jellyfish.yaml, assets/elements/item/kick_bomb/kick_bomb.yaml, assets/elements/item/mine/mine.yaml, assets/elements/item/musket/bullet/musket.bullet.yaml, assets/elements/item/musket/musket.yaml, assets/elements/item/sniper_rifle/bullet/sniper.bullet.yaml, assets/elements/item/sniper_rifle/musket.yaml, assets/elements/item/sword/sword.yaml, assets/game.yaml, assets/player/skins/fishy/fishy.player.yaml, assets/player/skins/orcy/orcy.player.yaml, assets/player/skins/pescy/pescy.player.yaml, assets/player/skins/sharky/sharky.player.yaml, packs/devpack/items/blunderbass/blunderbass.yaml, src/core/bullet.rs, src/core/elements/flappy_jellyfish.rs, src/core/elements/sproinger.rs, src/core/physics.rs, src/core/player.rs
**Overview:**
Delta time in physics update previously had a scale of 60 due to a prior fix regarding timestep.
This change removes the scaling of physics timestep by 60, and adjusts velocities / forces (gravity) to account for this so behavior does not change.
**Impact:**  Will help with ragdoll work I am doing, velocity metadata can be used with objects simulated in rapier and on our kinematics without having to get messy scaling them back and forth, or dealing with a very large timestep in rapier (which did not go well in my experiments).
units of velocity and gravity now relate more intuitively to position + sizes of objects in terms of setting velocity based on how far a contributor may want something to move per second.
**Changes:**
- velocities all scaled up by 60, gravity scaled up …
=> refactor(physics_timescale): Remove physics timestep scaled by 60 + update velocities to keep behavior

Cargo.lock, Cargo.toml, src/core/debug.rs, src/core/physics.rs, src/core/physics/collisions.rs, src/core/physics/dynamic_body.rs
This is the base of core changes to support ragdolls, allows us to simulate dynamic bodies in rapier.
DynamicBody component may be added to an entity that has KinematicBody, and if enabled, body will simulate physics. Transitioning between kinematic / dynamic and adjusting rapier data + collider is handled on next physics update.
This change should have no impact on existing kinematics, scene queries, etc. Usage of these changes will come in other PR soon.
**Switched to fork of rapier (temporarily hopefully):**
I switched us to a fork of rapier to fix a bug in which changing a rapier rigidbody from kinematic to dynamic will not put it in active dynamic set, so gravity is not applied. It seems they rely on contact graph to add body to this set, but if not in contact with anything it …
=> feat(physics): Support Dynamic bodies

Cargo.lock, Cargo.toml, src/core/physics/collisions.rs, src/core/physics/collisions/filtering.rs
Another chunk of features implemented to support ragdolls + dynamic bodies in Jumpy.
Add bit flags for rapier `CollisionGroup` and `SolverGroup`.
- The Collision group filters both contact forces and events, these are configured such that there is no change here in collision events.
- Solver group then filters contact forces, this is used to make sure dynamic actors only simulate collision with tiles (solid + jump through) and solids, not other kinematic (or dynamic) actors.
Dynamics collide with jump through tiles. A contact modification physics hook is implemented so dynamics moving upward through jump throughs have contact thrown out, and kept when falling.
- Only the contact filtering `PhysicsHook` is used, and is only enable on dynamic bodies while they are simulating.
I found that …
=> feat(physics): Contact filtering + changing shape + jump through for simulated bodies

Cargo.lock, assets/game.yaml, assets/locales/en-US/controls.ftl, assets/player/skins/fishy/fishy.player.yaml, assets/player/skins/orcy/orcy.player.yaml, assets/player/skins/pescy/pescy.player.yaml, assets/player/skins/sharky/sharky.player.yaml, src/core/attachment.rs, src/core/elements/sproinger.rs, src/core/metadata.rs, src/core/physics/collisions.rs, src/core/physics/collisions/shape.rs, src/core/player.rs, src/core/player/state.rs, src/core/player/state/states.rs, src/core/player/state/states/crouch.rs, src/core/player/state/states/dead.rs, src/core/player/state/states/idle.rs, src/core/player/state/states/midair.rs, src/core/player/state/states/ragdoll.rs, src/core/player/state/states/walk.rs, src/input.rs, src/settings.rs, src/ui/main_menu/settings/controls.rs
Player may toggle ragdoll state with `F` or `Right bumper`.
- player body switches to capsule and simulates physics in ragdoll state.
- movement during ragdoll twitches the body slightly, small velocity + animation change.
- set position with respect to parent no longer forced to 0 for all objects. Used this to tweak capsule position.
- Attached entities now rotate with parent.
This will need another pass, for now I re-used some stuff we have. Making the corpse more obviously dead would be good (though I guess being able to reasonably play dead may also be amusing). 
https://github.com/fishfolk/jumpy/assets/35712032/9bdcbc0c-146b-4339-a7bd-4ed1ca1bb44d
https://github.com/fishfolk/jumpy/assets/35712032/f9004638-fc03-4ee6-8e6f-0f7f0ab1f3a3 …
=> feat(ragdoll): Add player ragdoll state + corpse physics

src/core/player.rs, src/core/player/state/states/dead.rs, src/core/player/state/states/ragdoll.rs
Closes #930 
- Adds a `PlayerCommand` to drop a player's hat and reset its properties
- Replaces all instances of manually dropping a hat to use the new convenience command
=> fix: reset hat when dropped

Cargo.lock, assets/game.yaml, src/main.rs, src/ui/main_menu/map_select.rs
I opened a PR in bones to expose these settings for networking, instead of hard coding in engine. (https://github.com/fishfolk/bones/pull/354)
The defaults of these values were also changed in bones such that things are feeling much better in network play with ping around 100ms-150ms.
Now we may tune in metadata, though settings only take effect if new network match is created. This will not pass CI until bones PR is merged + bones version updated.
I think retuning this is a quick and big improvement for high-latency network play. I have WIP for visually smoothing corrections - but I think addressing core issues with networking and getting it as good as possible is priority vs trying to improve how corrections look. Will get that shipped at some point, but want to do some playtesting with …
=> fix(networking): Specify local input delay and max prediction window from metadata

assets/map/resources/ship_decorations.atlas.yaml, src/core/map.rs, src/core/physics/collisions.rs, src/core/physics/collisions/filtering.rs
define some collision info for jump through wood tiles, used to create accurate colliders for collision with ragdoll / dynamics.
The standard tile is still there for all intents and purposes. If there is an extra collider defined, this collider is also added, and is set to solver group such that dynamics will collider with it.
- This additional collider is not used for collision events.
- if additional collider is present, original tile collider no longer has solver group for collisions.
This fixes dynamics colliding with the invisible chunk on thin tiles such as jump through wood.
I think we're done with the trickle of auxiliary features and next PR should be ragdolls 😆
=> feat(physics): Add extra colliders to jump_through tiles for collision with dynamics

Cargo.lock, Cargo.toml, packs/devpack/pack.yaml
0.11.1 macOS x86_64 build failed during release - seemed related to dep on my fork of rapier, which we no longer need as PR was merged. Crossing my fingers that #946 resolved that issue and 0.11.2 goes smoothly.
=> chore(release): Bump to 0.11.2 for release / hopefully package all platforms successfully

Cargo.lock, Cargo.toml, deny.toml
Closes #951 
- De-duplicates dependencies:
- `async-lock`, `base64`, `getrandom`, `linux-raw-sys`, `parking_lot`, `parking_lot_core`, `rand`, `rand_chacha`, `rand_core`, `rustix`, `synstructure`, `wasi`
- Duplicates dependencies:
- `erased-serde`, `polling`
- Fixes security advisory due to `failure` crate removed from dependency tree
- All CI tasks now pass! 🎉 
---
<details>
<summary>Compare duplicated dependencies</summary>
<pre>
function get_dups() { cargo deny check 2>&1 | sed -En "s/^warning\\[duplicate].*('.*')/\1/p"; }
<br>
git switch main
get_dups > before.txt
<br>
git switch &lt;ref-you-want-to-compare-to-main&gt;
get_dups > after.txt
<br>
git diff --no-index before.txt after.txt
</pre>
</details>
=> feat: update packages

assets/elements/item/sniper_rifle/musket.yaml, packs/devpack/items/blunderbass/blunderbass.yaml, packs/devpack/items/blunderbass/bullet.yaml, packs/devpack/maps/devlevel_1.map.yaml
Found a few velocity-based meta values I missed in the #925 refactor.
=> fix: Fix musket/blunderbass kickback and blunderbass bullet speed being incorrect post-physics refactor

assets/elements/item/buss/buss.yaml, assets/elements/item/machine_gun/machine_gun.yaml, assets/elements/item/musket/musket.yaml, assets/elements/item/periscope/periscope.yaml, assets/elements/item/sniper_rifle/musket.yaml, src/core/elements/buss.rs, src/core/elements/machine_gun.rs, src/core/elements/musket.rs, src/core/elements/periscope.rs
I did what @MaxCWhitehead told me earlier, created a `bullet_spawn_offset` field in `.yaml`. I added this to all the weapons because it makes it easier for new contributors to locate and modify in case we change the artworks.
=> feat: bullet spawn offset in yaml

Cargo.lock, Cargo.toml
I've been frequently hitting a crash / bug in parry2d QBVH involving incremental update. Sometimes it crashes, sometimes is a framerate death spiral / fully locks up.
```
thread 'main' panicked at /Users/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parry2d-0.13.6/src/partitioning/qbvh/update.rs:367:54:
attempt to add with overflow
```
Appears to be been fixed at https://github.com/dimforge/parry/commit/7df2728afc8eff3c4ba7256b3344968481524b37 in parry2d 0.13.7. Updated rapier to use a fork with parry2d update as not updated in rapier yet.
=> fix(crash): Update parry2d to 0.13.7 (use rapier fork) for crash fix in QBVH

src/core/physics/collisions.rs
See #961 for context. There's a bug in parry2d involving incremental update failing to balance broadphase BVH. Fully rebuilding BVH avoids this issue, and we can get away with it due to few bodies in our game. This was our previous behavior before supporting dynamic bodies and relying on incremental update in physics pipeline, which turns out to be broken.
=> fix: Avoid physics query slowdown over time by rebuilding broadphase every frame

src/ui/network_game.rs
Focus a button by default so can be navigated without mouse. Fixes #939
=> fix(ui): Fix not being able to navigate online menu without mouse

Cargo.lock, src/core.rs, src/sessions.rs, src/ui/main_menu/map_select.rs
For map transitions, a session command restarting game session will be used after updating map.  This updates jumpy for related changes in: https://github.com/fishfolk/bones/pull/384
We can restart a networked game session by calling restart on session runner, which handles existing socket + match id increment, implemented on the bones side.
CI will fail until bones PR is merged + bones updated in lockfile.
=> fix: Preserve session_runner when restarting game session

src/core/elements/kick_bomb.rs, src/core/utils.rs, src/core/utils/metadata.rs
`commands.add(KickBombCommand::spawn_kick_bomb(Some(entity), transform, kick_bomb_meta_handle)` may be used to spawn a kick bomb.
- If entity is passed in it will initialize kick bomb components on this entity (mostly to support hydration from map elements), otherwise None will make it create an entity for you.
- The handle is untyped handle (can use `handle.untyped()` to convert to this), it supports `Handle<ElementMeta>` or `Handle<KickBombMeta>` automatically.
This command adds a `KickBombHandle` containing `Handle<KickBombMeta>`, this should be used to get meta for entities. The kick bomb systems now use this instead of `Handle<ElementMeta>`.
Gameplay systems were also updated such that usages of components `MapElementHydrated` and `DehydratedOutOfBounds` (things specific to map …
=> fix(kick_bomb): Add spawn kickbomb command to allow spawning from gameplay code without interfering with map hydration

src/core/elements/kick_bomb.rs
I broke hydration with in #968, accidentally marked things as hydrated even when element was not kick bomb / spawning was skipped.
=> fix: Fix kick bomb hydration breaking non-kickbomb spawned elements

src/core/elements/machine_gun.rs, src/core/elements/musket.rs
The musket simply didn't call `bullet_spawn_offset.y`, no big deal.
The machine gun animation would get frozen when dropped. Had to add an "else" for when the item is not being held, because `items_dropped.get` is called only when in fact the item got dropped, and if the player gets killed while shooting, the animation would still froze, as it wouldn't be IN FACT dropped.
It even made me think about the ammunition reload system of all guns.
```
if items_dropped.get(entity).is_some() {
// reload gun
gun.ammo = *max_ammo;
}
```
Here, reloading will only take place if the item is dropped. This means that if you die holding a musket with half the ammo, the next player to pick it up will get it with half the ammo. Is that what we really want? Or do we want the ammo to be reloaded?
=> fix: Fix machine gun animation and musket

src/core/elements/stomp_boots.rs
This PR closes #929.
I made `WornStompBoots` component that marks the entity that created when the player used the boots. When the player is killed (`PlayerKilled`) and a related entity with `WornStompBoots` exists (`stomp_boots` in `WearingStompBoots`), I respawn the entity with `StompBoots` component and remove marker `WornStompBoots`.
=> feat: Respawn Stamp Boots when a player was killed

src/ui/main_menu.rs, src/ui/main_menu/settings.rs, src/ui/pause_menu.rs
Does the minimal thing, I didn't change the code structure, but longer term I would suggest creating a place for shared menu options.
Closes #877,#999
=> feat: add settings menu to the in game menu

Cargo.lock, assets/locales/en-US/network-game.ftl, src/main.rs, src/sessions.rs, src/ui.rs, src/ui/notification.rs
During a game, if all other players have been disconnected, UI pop-up will notify player providing button to return to main menu.
If one player but not all have disconnected, going to have game keep going / figure out how to handle this separately. 
Relates to https://github.com/fishfolk/jumpy/issues/994, will not fix anything, but if hung due to disconnect, will inform player at least.
Depends on https://github.com/fishfolk/bones/pull/409, CI will fail until merged + update bones version.
=> fix: UI for leaving online game when disconnected

Cargo.lock, src/core.rs, src/ui/pause_menu.rs
Previously pausing in online would pause net loop and cause timeout. Now game continues to simulate in background, and inputs are disabled while pause menu open in online.
Dependent on https://github.com/fishfolk/bones/pull/411, CI will fail until updated.
Fixes https://github.com/fishfolk/jumpy/issues/1001
=> fix: Prevent pausing in online from timing out network, allow game to continue running

Cargo.lock, Cargo.toml, src/core.rs, src/core/elements/flappy_jellyfish.rs, src/core/elements/player_spawner.rs, src/core/input.rs, src/core/item.rs, src/core/player.rs, src/core/player/state/stage.rs, src/input.rs, src/ui/main_menu/map_select.rs, src/ui/main_menu/player_select.rs, src/ui/network_game.rs, src/ui/scoring.rs
matching PR to https://github.com/fishfolk/bones/pull/407
=> feat: update to bones with increase network player limit

src/ui/main_menu.rs
The version string widget was editable, and was stealing focus from menu nav.
=> fix: Fix losing focus on main menu when pressing right/left

src/ui/main_menu/player_select.rs
Remove ability to add AI player to first slot, reserved for at least one player.
FIx being able to start game without a real player.
Closes #974  and #956
=> fix(player_select): Fix adding AI in first slot + starting game with AI but no player

src/ui/pause_menu.rs
=> fix(pause_menu): Remove Map "Edit" button from pause menu until map editor restored

src/ui/pause_menu.rs
=> fix: Make sure pause menu closes after a menu map change

Cargo.lock, src/audio.rs, src/audio/music.rs, src/sessions.rs, src/settings.rs, src/ui/main_menu/settings/audio.rs
Use AudioCenter from bones now that it has been moved there, and remove from Jumpy.
Added a trait extension to continue playing music from kira `StaticSoundSettings`, to avoid having to put all of the params in `play_music_advanced`, as the looping is configured a bit differently.
The addition of `force_restart` in PlayMusic event has been helpful, now music does not restart each time switch menu pages.
Resolves #1016
=> fix: Switch to AudioCenter implemented in bones - remove from Jumpy

Cargo.lock
fixes https://github.com/fishfolk/jumpy/security/dependabot/17
=> chore(deps): bump quinn-proto to >0.11.7

.github/workflows/release.yml
fixes https://github.com/fishfolk/jumpy/security/dependabot/18
(we should probably update the other actions too)
=> chore(ci): bump actions/download-artifact to v4

.github/workflows/release.yml
We updated download-artifacts to v4 but not upload, seems to have broken release pipeline, hopefully this fixes.
=> chore: bump actions/upload-artifacts  to v4

Cargo.lock, Cargo.toml, src/core/elements/flappy_jellyfish.rs, src/core/random.rs, src/ui/main_menu/map_select.rs, src/ui/main_menu/player_select.rs, src/ui/network_game.rs
This updates bones and uses new matchmaking flow. Includes using the new matchmaker rng seed, and gilrs update.
Some other little fixes included:
- "Waiting for players" text now displays again when matchamaking
- If start matchmaking online and switch to lan tab, matchmaking is now cancelled.
Gilrs update confirmed fixes: #989
=> feat: Update bones - new matchmaker flow + rng seed, gilrs input update

src/input.rs, src/ui/main_menu/settings/networking.rs
Fixes #933 
Disabling only gamepad input seems to make the input behave as one would expect. Arrow keys, backspace, etc work like normal, and bound keys (e.g. A, D) only update the text and no longer move the caret.
Unfortunately I don't have a controller to test with, but I assume this will work with those kind of inputs too.
=> fix(settings): networking tab input

src/ui/main_menu.rs
Replace `std::process::exit(0)` with proper use of the `bones::ExitBones` resource.
=> fix: use `bones::ExitGame` to quit

.gitattributes, Cargo.lock, assets/locales/en-US/player-select.ftl, deny.toml, src/ui/main_menu/map_select.rs, src/ui/main_menu/player_select.rs, src/ui/main_menu/settings/controls.rs
Fixes #963
- [6781542](https://github.com/fishfolk/jumpy/pull/1037/commits/6781542946af7aafdaf0fe69ce0cf7cdd63b0781) `PlayerSlot` is now (sort of) a state machine, starting out `Empty` then progressing through `SelectingPlayer` and `SelectingHat` until becoming `Ready`
- Slot for a network player only uses the `SelectingHat` and `Ready` states for simplicity
- Angled brackets `<` and `>` show around the thing being selected (player/hat), brackets now don't show when ready
- [a2393c4](https://github.com/fishfolk/jumpy/pull/1037/commits/a2393c462d54a45c3b66d92d1b02559b435504aa) fix bug where label has incorrect text for 1 frame when pressing Menu Back to remove player from slot
- [f636d33](https://github.com/fishfolk/jumpy/pull/1037/commits/f636d3308832777d6714bceaba18c7e9e169da15) Upgrade …
=> fix: require hat select before ready up

src/ui/main_menu/player_select.rs
Fixes #1036 and couple other things along the way
Not entirely sure what caused this - but I think I introduced it when updating for new matchmaker interface in bones.
We would allow online matches to continue if >1 players are ready and no unconfirmed players. The issue is that in online remote players who had not made a selection were in `Empty` state, and not tracked as unconfirmed. Now for any local + required players, I initialize them to new PlayerSlot type `SelectingLocalControlSource`. `Empty` may be used for online slots that are unused (the last 2 slots in a 2 player game) in online, or for lan, optional slots that may be joined by additional players/AI, but are not required. And remote required players are set to `SelectingPlayer` with default fish + no hat - as next message …
=> fix(player_select): Fix Online game able to start without all playes ready 

assets/map/levels/level_6.map.yaml
Fixes #990.
Reorder the spawners in the level asset so that players 1 & 2 spawn on opposite sides of the map.
=> fix(map): order of level 6 spawners
